export SUBVERSION_VERSION=1.11.1
export SUBVERSION_HOME=/usr/share/subversion/subversion-${SUBVERSION_VERSION}
export SUBVERSION_DATA ${SUBVERSION_HOME}/data
export SUBVERSION_PORT 32182

export PATH=${PATH}:${SUBVERSION_HOME}/bin

