version: '3.7'

services:

  # application:
  #   container_name: ${NAMES[0]}
  #   image: ${IMAGES[0]}
  #   user: ${USERS[0]}
  #   ports: ['${PORTS[0]}:${PORTS[0]}']
  #   volumes:
  #     # - ./config/application/*.tar.gz:/usr/share/analytic/*.tar.gz
  #     # - ./config/application/service.sh:/usr/share/analytic/service.sh
  #     - application-data:${PATHS[0]}/data
  #   #restart: always
  #   depends_on: ['artifactory']
  #   networks: ['${NETWORKS[0]']
  
  # artifactory:
  #   container_name: ${NAMES[1]}
  #   image: ${IMAGES[1]}
  #   user: ${USERS[1]}
  #   ports: ['${PORTS[1]}:${PORTS[1]}']
  #   volumes:
  #     - artifactory-data:${PATHS[1]}/data
  #   #restart: always
  #   networks: ['${NETWORKS[0]']

  # gitlab:
  #   container_name: gitlab
  #   image: ghandalf/gitlab:${CONTAINERS_VERSION}
  #   hostname: gitlab.dmi.com
  #   user: gituser
  #   ports: ['32182:32182']
  #   volumes:
  #     - gitlab-data:${PATHS[2]}/data
  #   #restart: always
  #   networks: ['pipeline_net']

    # user/password=admin/74cbc0107e0e4efca7a4d98c8395743b
  # Jenkins running under jdk 11: https://jenkins.io/blog/2018/12/14/java11-preview-availability/
  jenkins:
    container_name: jenkins
    image: ghandalf/jenkins:${CONTAINERS_VERSION}
    hostname: jenkins
    user: jenkinsuser
    ports: ['32183:32183']
    volumes:
      # - ./config/jenkins/system/jenkins.sh:/usr/profile.d/jenkins.sh
      # - ./config/jenkins/system/service.sh:/usr/share/jenkins/bin/sercice.sh
      - jenkins-data:/usr/share/jenkins/data
    #restart: always
    # depends_on: ['git', 'artifactory']
    networks: ['pipeline_net']
    
volumes:
  application-data:
    driver: local
  artifactory-data:
    driver: local
  gitlab-data:
    driver: local
  jenkins-data:
    driver: local

networks: { pipeline_net:{} }
